let enterpriseUnits = [
    {
        id: '1',
        stage: 'Etapa 1',
        block: 'Maragogi',
        numberRooms: '3',
        floor: '3',
        totalArea: '32,99 m2',
        column: '15',
        status: 'Disponível',
        price: '300.000,00'
    },
    {   
        id: '2',
        stage: 'Etapa 1',
        block: 'Trancoso',
        numberRooms: '3',
        floor: '3',
        totalArea: '32,99 m2',
        column: '12',
        status: 'Disponível',
        price: '350.000,00'
    },
    {
        id: '3',
        stage: 'Etapa 2',
        block: 'Noronha',
        numberRooms: '2',
        floor: '5',
        totalArea: '54,58 m2',
        column: '14',
        status: 'Reservada',
        price: '210.000,00'
    },
    {   
        id: '4',
        stage: 'Etapa 3',
        block: 'Maragogi',
        numberRooms: '2',
        floor: '5',
        totalArea: '32,99 m2',
        column: '14',
        status: 'Vendida',
        price: '280.000,00'
    },
    {   
        id: '5',
        stage: 'Etapa 4',
        block: 'Arraial do cabo',
        numberRooms: '2',
        floor: '6',
        totalArea: '54,58 m2',
        column: '13',
        status: 'Disponível',
        price: '270.000,00'
    },
    {   
        id: '6',
        stage: 'Etapa 1',
        block: 'Carneiros',
        numberRooms: '2',
        floor: '2',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Vendida',
        price: '310.000,00'
    },
    {   
        id: '7',
        stage: 'Etapa 4',
        block: 'Maragogi',
        numberRooms: '3',
        floor: '7',
        totalArea: '32,99 m2',
        column: '14',
        status: 'Reservada',
        price: '343.000,00'
    },
    {   
        id: '8',
        stage: 'Etapa 3',
        block: 'Trancoso',
        numberRooms: '3',
        floor: '8',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Vendida',
        price: '180.000,00'
    },
    {   
        id: '9',
        stage: 'Etapa 2',
        block: 'Maragogi',
        numberRooms: '3',
        floor: '7',
        totalArea: '32,99 m2',
        column: '14',
        status: 'Reservada',
        price: '313.000,00'
    },
    {   
        id: '10',
        stage: 'Etapa 4',
        block: 'Trancoso',
        numberRooms: '3',
        floor: '8',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Reservada',
        price: '298.000,00'
    },
    {   
        id: '11',
        stage: 'Etapa 2',
        block: 'Trancoso',
        numberRooms: '3',
        floor: '8',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Bloqueada',
        price: '298.000,00'
    },
    {   
        id: '12',
        stage: 'Etapa 1',
        block: 'Trancoso',
        numberRooms: '3',
        floor: '8',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Disponível',
        price: '298.000,00'
    },
    {   
        id: '13',
        stage: 'Etapa 1',
        block: 'Trancoso',
        numberRooms: '3',
        floor: '8',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Reservada',
        price: '299.000,00'
    },
    {   
        id: '14',
        stage: 'Etapa 1',
        block: 'Trancoso',
        numberRooms: '3',
        floor: '8',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Bloqueada',
        price: '268.000,00'
    },
    {   
        id: '15',
        stage: 'Etapa 1',
        block: 'Trancoso',
        numberRooms: '3',
        floor: '8',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Vendida',
        price: '368.000,00'
    },
    {   
        id: '16',
        stage: 'Etapa 1',
        block: 'Arraial do cabo',
        numberRooms: '3',
        floor: '8',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Vendida',
        price: '368.000,00'
    },
    {   
        id: '17',
        stage: 'Etapa 1',
        block: 'Arraial do cabo',
        numberRooms: '3',
        floor: '8',
        totalArea: '46,59 m2',
        column: '16',
        status: 'Vendida',
        price: '468.000,00'
    },
    {
        id: '17',
        stage: 'Etapa 1',
        block: 'Noronha',
        numberRooms: '4',
        floor: '7',
        totalArea: '64,58 m2',
        column: '14',
        status: 'Vendida',
        price: '210.000,00'
    },
    {
        id: '18',
        stage: 'Etapa 1',
        block: 'Noronha',
        numberRooms: '5',
        floor: '7',
        totalArea: '74,58 m2',
        column: '14',
        status: 'Disponível',
        price: '210.000,00'
    },
    {   
        id: '19',
        stage: 'Etapa 1',
        block: 'Arraial do cabo',
        numberRooms: '3',
        floor: '8',
        totalArea: '36,59 m2',
        column: '16',
        status: 'Disponível',
        price: '668.000,00'
    },
    {   
        id: '20',
        stage: 'Etapa 1',
        block: 'Arraial do cabo',
        numberRooms: '1',
        floor: '2',
        totalArea: '26,59 m2',
        column: '16',
        status: 'Bloqueada',
        price: '168.000,00'
    },
    {   
        id: '21',
        stage: 'Etapa 1',
        block: 'Arraial do cabo',
        numberRooms: '1',
        floor: '2',
        totalArea: '26,59 m2',
        column: '16',
        status: 'Reservada',
        price: '268.000,00'
    },
    {   
        id: '22',
        stage: 'Etapa 1',
        block: 'Carneiros',
        numberRooms: '1',
        floor: '2',
        totalArea: '26,59 m2',
        column: '16',
        status: 'Reservada',
        price: '268.000,00'
    },

    {
        id: '23',
        stage: 'Etapa 1',
        block: 'Carneiros',
        numberRooms: '4',
        floor: '7',
        totalArea: '64,58 m2',
        column: '14',
        status: 'Vendida',
        price: '210.000,00'
    },
    {
        id: '24',
        stage: 'Etapa 1',
        block: 'Carneiros',
        numberRooms: '5',
        floor: '7',
        totalArea: '74,58 m2',
        column: '14',
        status: 'Disponível',
        price: '210.000,00'
    },
    {   
        id: '25',
        stage: 'Etapa 1',
        block: 'Carneiros',
        numberRooms: '3',
        floor: '8',
        totalArea: '36,59 m2',
        column: '16',
        status: 'Bloqueada',
        price: '668.000,00'
    },

];